steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "Frontend"
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "Backend"

options:
  logging: CLOUD_LOGGING_ONLY